### ISSUE TITLE
Null pointer exeption

### ISSUE THREAD

**Issue by Andful** [twalgor/tw#2]
Currently the following code throws an exeption
```Java
Graph g = Graph.readGraph(new File(args[0]));
ACSDecBrute acsd = new ACSDecBrute(g);
acsd.decomposeByACS();
```
With the following stack trace:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "io.github.twalgor.heap.Queueable.setHeapIndex(int)" because "this.h[i]" is null
	at io.github.twalgor.heap.Heap.remove(Heap.java:53)
	at io.github.twalgor.greedy.MMD.order(MMD.java:199)
	at io.github.twalgor.greedy.MMD.triangulate(MMD.java:45)
	at io.github.twalgor.acsd.ACSDecBrute.cliqueSeps(ACSDecBrute.java:113)
	at io.github.twalgor.acsd.ACSDecBrute.decomposeByACS(ACSDecBrute.java:59)
	at io.github.twalgor.acsd.ACSDecBrute.main(ACSDecBrute.java:169)
```
I tested the code with the Pace challenge  2017 graph ex004.gr

**Comment by Andful** [comment]
Actually the same happens in `io.github.twalgor.main.ACSD.main` with the following stack trace
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "io.github.twalgor.heap.Queueable.setHeapIndex(int)" because "this.h[i]" is null
	at io.github.twalgor.heap.Heap.remove(Heap.java:53)
	at io.github.twalgor.greedy.MMD.order(MMD.java:199)
	at io.github.twalgor.greedy.MMD.triangulate(MMD.java:45)
	at io.github.twalgor.acsd.ACSDecomposition.candidateSeps(ACSDecomposition.java:65)
	at io.github.twalgor.acsd.ACSDecomposition.decomposeByACS(ACSDecomposition.java:74)
	at io.github.twalgor.main.ACSD.main(ACSD.java:37)
```
With the arguments `-MMD ex004.gr out.txt`
